### PR TITLE
use new header support

### PR DESCRIPTION
**Pull request by steveklabnik**

### CODE REVIEW

**Comment by matthewjasper** [comment]
This is part of #173?

**Comment by steveklabnik** [comment]
that's the intention, yeah. doing some testing, i'm not 100% sure this is ready to be merged...

**Comment by Havvy** [comment]
This PR is losing the warning styles. And my PR is affected by https://github.com/rust-lang-nursery/mdBook/issues/585.

**Comment by steveklabnik** [comment]
i didn't realize 173 was a PR and not a tracking issue! let's go with that.

**Pull request closed without merging**
