### PR TITLE
Add pub(restricted) docs

### PR DESCRIPTION
**Pull request by cramertj**
See rust-lang/rust#32409
cc @steveklabnik

### CODE REVIEW

**Comment by steveklabnik** [comment]
This text looks good to me! I'm going to have to think about CI....

**Comment by petrochenkov** [comment]
Could you add three more details
- `path` in `pub(in path) item` must be some parent module of the item.
- `pub(super)` and `pub(self)` are shortcuts for `pub(in super)` and `pub(in self)` respectively
- `pub(self)` is the same thing as private

**Comment by cramertj** [comment]
@petrochenkov Is there some reason to use `pub(self)` that I should mention? It doesn't seem well-motivate to me.

**Comment by petrochenkov** [comment]
@cramertj 
Not yet (but see https://github.com/rust-lang/rust/issues/32770), but it's useful for understanding the model.

**Comment by steveklabnik** [comment]
blocked on https://github.com/rust-lang-nursery/reference/issues/14

**Comment by steveklabnik** [comment]
Update: this is now unblocked, but we need the feature to stabilize to land.

**Comment by petrochenkov** [comment]
@steveklabnik 
Everything is stabilized already, these docs are the only missing part.

**Comment by steveklabnik** [comment]
@petrochenkov running in nightly without the flag still requires the flag. Maybe my nightly was out of date?

**Comment by steveklabnik** [comment]
Ah, it was. My bad!

**Comment by steveklabnik** [comment]
@cramertj can you rebase this please? We can then get it in.

**Comment by cramertj** [comment]
Something weird is going on with the tests-- Travis is complaining that it can't find `outer_mod` in the crate root, but it works just fine when I run it on the playground or using rustc locally. Any ideas?

**Comment by matthewjasper** [comment]
You need to add `# fn main() {}` to the example otherwise everything gets wrapped in `main`.

**Comment by cramertj** [comment]
@matthewjasper lol ty

**Comment by steveklabnik** [comment]
Thanks!

**Pull request merged**
