### PR TITLE
Create book.toml

### PR DESCRIPTION
**Pull request by matthewjasper**
This makes the pages have the correct title. (Rather than 'Introduction - ' and similar).

### CODE REVIEW

**Comment by matthewjasper** [comment]
CC rust-lang/book#487

**Comment by steveklabnik** [comment]
What's book.json? I can't find any reference to it in mdbook's docs.

**Comment by matthewjasper** [comment]
I just copy pasted from the book repo. It's mentioned [here](https://docs.rs/mdbook/0.0.17/mdbook/book/struct.MDBook.html#method.read_config) though.

**Comment by steveklabnik** [comment]
Thank you!

**Pull request merged**
