### PR TITLE
Add appendix for list of undocumented features

### PR DESCRIPTION
**Pull request by mrhota**
Re: #9 

r? @steveklabnik 

CC @chriskrycho

### CODE REVIEW

**Comment by steveklabnik** [comment]
This is an interesting idea; @chriskrycho do you think this is helpful?

**Comment by mrhota** [comment]
@steveklabnik I think this is actually a requirement of the RFC for #9. The quotation at the top of the issue mentions it, with another mention in section C.1.

**Comment by chriskrycho** [comment]
Quite! So much so that RFC 1636 said we'd do exactly this:

> Updating the reference should proceed stepwise:
> 
> 1. Begin by adding an appendix in the reference with links to all accepted RFCs which have been implemented but are not yet referenced in the documentation.
> 2. As the reference material is written for each of those RFC features, remove it from that appendix.

**Comment by chriskrycho** [comment]
I've integrated these into the tracking issue; thanks again for the help!

**Pull request merged**
