### PR TITLE
Import #[repr(transparent)] docs from the Unstable book

### PR DESCRIPTION
**Pull request by SimonSapin**
… as the feature is ready for stabilization: https://github.com/rust-lang/rust/issues/43036#issuecomment-394094318

### CODE REVIEW

**Comment by rkruppe** [comment]
I don't think this text really fits into the reference, as it explains a lot of motivation and background rather than precisely and concisely stating what the attribute does. Certainly when I wrote it I had something like The Book or RBE in mind, not the reference.

**Comment by SimonSapin** [comment]
Feature stabilization PR: https://github.com/rust-lang/rust/pull/51395

I agree that the subsections do not necessarily belong there as-is but I wasn’t sure what else to do, this PR is sort of a straw man.

**Comment by alercah** [comment]
I agree that this is not ready for integration into the reference. Adding more/confusing text is not necessarily better, even if it improves coverage.

**Comment by Havvy** [comment]
Closing in favor of #389 since the RFC's contents don't translate to being in the reference directly that well.

**Pull request closed without merging**
