### PR TITLE
Fixups for token ref

### PR DESCRIPTION
**Pull request by bstrie**
Various minor fixes and additions.

### CODE REVIEW

**Comment by Havvy** [comment]
@bstrie Can you rebase this (and your other PR) against master so that CI actually works properly?

**Comment by bstrie** [comment]
@Havvy is rebasing all that I need to do? According to Github there are no conflicts with the base branch, so I'm not actually sure what's causing CI to choke.

**Comment by bstrie** [comment]
Rebased.

**Comment by Havvy** [comment]
💟 Thanks!

**Pull request merged**
