### PR TITLE
Rename glossory to glossary (o->a)

### PR DESCRIPTION
**Pull request by Havvy**

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Should we check for links that may point here, or would it prudent to do that checking when it's merged upstream?

**Comment by Havvy** [comment]
It's a relatively new addition to the reference, so I doubt anybody has linked to it from the stdlib and definitely not the other books.

**Comment by Havvy** [comment]
This is going to cause merge conflicts with #128 one way or another, and also conflicts with a PR I want to submit, but am waiting on this one for.

**Comment by steveklabnik** [comment]
@Havvy ping on this!

**Comment by Havvy** [comment]
Rebased.

**Pull request merged**
