### PR TITLE
Add doc-alias documentation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Part of https://github.com/rust-lang/rust/pull/63236

### CODE REVIEW

**Comment by Centril** [comment]
Why is this being added here?

It's both unstable and AFAIK not part of Rust the language. The only part that is part of the language is that the compiler is aware that a `doc` attribute exists and not what form `$tts` may take in `#[doc($tts)]`.

**Comment by GuillaumeGomez** [comment]
It's part of the stabilization process as far as I can tell. Also, it's an attribute so it seems to be at its place or did I miss something?

**Comment by Centril** [comment]
The reference is meant to specify Rust the language, not rustdoc specific things. I would prefer to just mention that `#[doc]` exists and then link to some other source, e.g. rustdoc specific documentation.

cc @ehuss

**Comment by ehuss** [comment]
Yea, we only briefly mention the `doc` attribute in https://doc.rust-lang.org/nightly/reference/attributes.html and defer to https://doc.rust-lang.org/rustdoc/the-doc-attribute.html for the actual documentation.  It looks like your rustdoc PR already updates that page, so I would say this is not necessary.

**Comment by GuillaumeGomez** [comment]
Fine by me. Just close the PR if it's your final decision. :smiley:

**Comment by Centril** [comment]
Alright; thanks!

**Pull request closed without merging**
