### PR TITLE
Mention the global_allocator trait

### PR DESCRIPTION
**Pull request by brson**
I don't know much about the organization of this book, but this seems an ok place to put it.

cc https://github.com/rust-lang/rust/pull/51974

### CODE REVIEW

**Comment by brson** [comment]
I didn't know how to link `GlobalAlloc`.

**Comment by steveklabnik** [comment]
This should be on hold until https://github.com/rust-lang/rust/pull/51974#issuecomment-401678445

**Comment by Havvy** [comment]
I don't see how that comment relates to the contents of this PR. It doesn't mention what the default allocator is either.

**Comment by Havvy** [comment]
Given that `global_alloc` is stable, better to have at least a stub of documentation vs. no documentation at all. We want the list to at least be complete.

**Pull request merged**
