### PR TITLE
Add union items to the reference

### PR DESCRIPTION
**Pull request by petrochenkov**
Copy-pasted from https://github.com/rust-lang/rfcs/pull/1897

### CODE REVIEW

**Comment by steveklabnik** [comment]
Unions are not yet stable, so we'll have to wait until they are to merge.

**Comment by petrochenkov** [comment]
@steveklabnik 
So, the stabilization PR (https://github.com/rust-lang/rust/pull/42068) can land before this one? Ok.

**Comment by steveklabnik** [comment]
Yup! Sending in this PR is enough to satisfy the requirement of stabilizing the feature. Then it lands, then we land tihs.

**Comment by frewsxcv** [comment]
Just reran Travis and this passes now. The contents of the PR look good to me. Seems good to merge?

**Comment by steveklabnik** [comment]
Yup!

**Pull request merged**
