### PR TITLE
Fix never type link

### PR DESCRIPTION
**Pull request by MajorBreakfast**
This PR fixes the inconsistent spelling that currently breaks the link.

### CODE REVIEW

**Comment by MajorBreakfast** [comment]
This accidentally also contains stuff from my other PR. Fixing now...

**Comment by MajorBreakfast** [comment]
Ok now it contains just the one change I wanted to make.

**Comment by alercah** [comment]
I'd almost rather the never type link be broken, because of it being unstabilized. Hm.

**Comment by MajorBreakfast** [comment]
Maybe remove the never type section entirely?

**Comment by alercah** [comment]
If you want to take on #344, that would be awesome! But don't feel like you have to. :)

**Comment by MajorBreakfast** [comment]
👍

**Pull request closed without merging**
