### PR TITLE
Fixed non-escaped *s in grammar

### PR DESCRIPTION
**Pull request by brauliobz**
Those break mbook's parsing sometimes.

### CODE REVIEW

**Comment by Havvy** [comment]
How do these break mdbook's parsing? Is it a Mardown thing, or an issue in mdbook?

**Comment by matthewjasper** [comment]
@brauliobz, can you rebase so that this can be merged, unless @Havvy has any objections.

**Comment by brauliobz** [comment]
@matthewjasper Done.

**Comment by matthewjasper** [comment]
Thanks!

**Pull request merged**
