### PR TITLE
Add note about anon params

### PR DESCRIPTION
**Pull request by mark-i-m**
cc @Centril @steveklabnik  https://github.com/rust-lang/rust/issues/41686

### CODE REVIEW

**Comment by Centril** [comment]
@steveklabnik I'd like the reference to be more specification-like at some point including using BNF formalisms to define things like these; but for now, this seems good enough. :)

**Comment by Havvy** [comment]
I sent a PR against your branch. https://github.com/mark-i-m/reference/pull/1

**Comment by mark-i-m** [comment]
Thanks @Havvy! Sorry I'm a bit sluggish. I'm in a bit of time crunch.

**Comment by Havvy** [comment]
No need to apologize. You're not moving slower than anybody else on this repo. I just felt like making the changes, so I did..

**Comment by mark-i-m** [comment]
@Havvy Perhaps this can be merged now?

**Comment by Havvy** [comment]
I generally don't like merging things where I've sent commits.

**Comment by matthewjasper** [comment]
Thank you both!

**Pull request merged**
