### PR TITLE
Add linkchecker.

### PR DESCRIPTION
**Pull request by ehuss**
This is a little gumby, but it works.

It:
- Downloads linkchecker from rust-lang/rust.
- Copies the HTML pages from nightly rustup, which should be a close reflection of how they look on doc.rust-lang.org.
- Build and copies the reference.
- Runs the linkchecker.

### CODE REVIEW

**Comment by Havvy** [comment]
@Mark-Simulacrum Is this in your review queue?

**Comment by Mark-Simulacrum** [comment]
It wasn't, but I will try to review it this week. Sorry for missing it earlier!

**Comment by Mark-Simulacrum** [comment]
This looks reasonable to me, though I would expect spurious failures somewhat regularly.

**Comment by Havvy** [comment]
I don't think anybody else is going to review this, nor are there any known stoppers, so let's try it and see what happens.

**Pull request merged**
